# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@master
      with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
    - run: sh public_package.sh
      env:
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}
