name: npm publish CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@master
      with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
    - run: |
        echo '安装依赖'
        npm install
        echo '删除旧的打包文件'
        rm -rf ./dist
        sleep 2
        echo '执行打包！'
        npm run build
        sleep 2
        echo '切换正常源！'
        npm config set registry http://registry.npmjs.org
        sleep 2
        echo '复制发布文件！'
        cp package.json ./dist/package.json
        sleep 2
        cp README.md ./dist/README.md
        sleep 2
        npm publish ./dist
      env:
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}
